products = [
  {
    '_id': '1',
    'name': 'Differential YA-81M',
    'image': '/images/differential.jpg',
    'description': 'High-quality differential gear set for improved vehicle performance and durability.',
    'brand': 'VAZ',
    'category': 'Transmission',
    'price': 299.99,
    'countInStock': 15,
    'rating': 4.7,
    'numReviews': 23,
  },
  {
    '_id': '2',
    'name': 'GearBox UT-9243',
    'image': '/images/gearbox.jpg',
    'description': 'Robust gear box designed for smooth and efficient transmission of power.',
    'brand': 'Opel',
    'category': 'Transmission',
    'price': 499.99,
    'countInStock': 8,
    'rating': 4.4,
    'numReviews': 16,
  },
  {
    '_id': '3',
    'name': 'Headlights TQ-51RS',
    'image': '/images/headlights.jpg',
    'description': 'Premium headlights for better visibility and safety.',
    'brand': 'Ferrari',
    'category': 'Lighting',
    'price': 149.99,
    'countInStock': 25,
    'rating': 4.8,
    'numReviews': 30,
  },
  {
    '_id': '4',
    'name': 'Engine RB26',
    'image': '/images/engine.jpg',
    'description': 'Complete engine for powerful and efficient performance.',
    'brand': 'Porche',
    'category': 'Engine',
    'price': 1299.99,
    'countInStock': 10,
    'rating': 4.9,
    'numReviews': 15,
  },
  {
    '_id': '5',
    'name': 'Intercooler WRX-STI',
    'image': '/images/intercooler.jpg',
    'description': 'High-performance intercooler for improved engine cooling.',
    'brand': 'Subaru',
    'category': 'Cooling',
    'price': 249.99,
    'countInStock': 12,
    'rating': 4.6,
    'numReviews': 20,
  },
  {
    '_id': '6',
    'name': 'Exhaust Manifold GA21',
    'image': '/images/manifold.jpg',
    'description': 'High-quality exhaust manifold for improved engine performance and durability.',
    'brand': 'Audi',
    'category': 'Exhaust',
    'price': 179.99,
    'countInStock': 18,
    'rating': 4.3,
    'numReviews': 22,
  },
  {
    '_id': '7',
    'name': 'Power Steering Pump UI96-NT2',
    'image': '/images/powersteering.jpg',
    'description': 'Efficient power steering pump for easy and precise vehicle handling.',
    'brand': 'Mercedes',
    'category': 'Steering',
    'price': 229.99,
    'countInStock': 14,
    'rating': 4.6,
    'numReviews': 19,
  },
  {
    '_id': '8',
    'name': 'Seat TOYOTA-YR-43',
    'image': '/images/seat.jpg',
    'description': 'Comfortable and durable car seat for enhanced driving experience.',
    'brand': 'Toyota',
    'category': 'Interior',
    'price': 119.99,
    'countInStock': 22,
    'rating': 4.5,
    'numReviews': 25,
  },
  {
    '_id': '9',
    'name': 'Wheels RENO-221',
    'image': '/images/wheel.jpg',
    'description': 'Stylish and durable wheel rim for improved vehicle aesthetics and performance.',
    'brand': 'Reno',
    'category': 'Wheels',
    'price': 89.99,
    'countInStock': 35,
    'rating': 4.7,
    'numReviews': 32,
  },
  {
    '_id': '10',
    'name': 'Windshield VW-FD37',
    'image': '/images/windshield.jpg',
    'description': 'High-quality windshield for clear visibility and safety.',
    'brand': 'Volkswagen',
    'category': 'Glass',
    'price': 159.99,
    'countInStock': 28,
    'rating': 4.8,
    'numReviews': 27,
  },
]

